version: "3.9"

services:
  db:
    image: postgres:16
    container_name: semaforo_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: semaforo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: semaforo_app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: semaforo
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "8080:3000"

volumes:
  db_data: